### PR TITLE
Bugfix/tshig mdzod chen mo wa zur

### PR DESCRIPTION
**Pull request by nbuwe**
tshig mdzod chen mo ended up with wa-zur merged with lengthening 'a-chung, so e.g. both r'a and rva ended up as rA.  This branch is an attempt to gauge whether fixing this manually is feasible.  I'm creating a draft PR just to provide a cross-reference visible from the parent repo.

### CODE REVIEW

**Comment by nbuwe** [comment]
I'm reasonably happy with these fixes.  I now have second thoughts about a few changes where I trimmed entries b/c the trailing Tibetan was just Tibetan letters quoted in Chinese part of the entries, and so they make no sense plucked out of context.  But that introduces unnecessary diffs that you have to keep in mind during the review.  Might be better to restore them.

**Comment by christiansteinert** [comment]
Dear Valery

First of all thanks a lot for all your work.

I think it's good to keep the removal of these stray letters as it is. 

Are these contained in a few commits so that I can recognize them more easily? Even if not it would be a shame to lose these fixes...


Many thanks
Christian 

Am 2. Januar 2023 01:10:58 MEZ schrieb Valery Ushakov ***@***.***>:

**Comment by nbuwe** [comment]
[2f562b0](https://github.com/christiansteinert/tibetan-dictionary/pull/11/commits/2f562b0d9867fce220aed3ad7d7c519a530ebc85) for wa btags
[0ccd751](https://github.com/christiansteinert/tibetan-dictionary/pull/11/commits/0ccd75141159d8d1794c61fb879a8d02f8e4b787) for tsa lag

**Comment by christiansteinert** [comment]
Thanks for your meticulous work. This is extremely helpful and greatly appreciated.
The PR is really a huge improvement to fixe the messy wazurs. Thanks also for taking care of some other things such as misparsed shad's that you stumbled across which caused incorrect headwords.

I noticed that SHa / DHa should actually be Sha / Dha but I will fix this in the main branch after merging. 
Also, I noticed that the original file in some cases contains a'a rather than A but again I fill fix this in the main branch.

Many, many thanks for your help and for the time and care you have put into this!
Christian

**Comment by nbuwe** [comment]
`a'a` is the original ACIP transliteration that explicitly uses `a` for the "consonant" and then another `a` for the vowel.  Thus, e.g. ACIP would use `aa ce` for ཨ་ཅེ་

**Comment by christiansteinert** [comment]
Good point but in this file a'a is actually often used to represent a long a.

For example, "Āryadeva" was transliterated as "a'a rya de wa" or "āli kāli" was transliterated as "a'a li ka'a li" so I adjusted those instances.

**Comment by nbuwe** [comment]
Exactly, the first `a` is the "consonant", the `'` is the lengthening 'a-chung, and the second `a` is the (implicit) vowel.  Thus `a'a` is the correct ACIP transliteration for ཨཱ་

**Comment by nbuwe** [comment]
PS: What I meant to say is that "a'a rather than A" is the norm for the original data (or rather "A'A" b/c it was all upper case by default)

**Pull request merged**
